<?php
	return [
		'affiliate_review' => [
            'subject' => 'Your affiliate account is currently under review',
            'content' => 'mails.affiliates.affiliate_review',
            'slug' => 'affiliate_review',
            'status' => 1,
            'name' => 'Affiliate review',
        ],
		'approved_affiliate' => [
            'subject' => 'Your application to our affiliate program has been approved',
            'content' => 'mails.affiliates.approved_affiliate',
            'slug' => 'approved_affiliate',
            'status' => 1,
            'name' => 'Approved affiliate',
        ],
		'denied_affiliate' => [
            'subject' => 'Your application to our affiliate program has been denied',
            'content' => 'mails.affiliates.denied_affiliate',
            'status' => 1,
            'slug' => 'denied_affiliate',
            'name' => 'Denied affiliate',
        ],
        'affiliate_verification' => [
            'subject' => 'Welcome! Verify your email to get started',
            'content' => 'mails.affiliates.affiliate_verification',
            'slug' => 'affiliate_verification',
            'status' => 1,
            'name' => 'Affiliate verification',
        ],

		'new_conversion' => [
            'subject' => 'Congrats! You have a new conversion.',
            'content' => 'mails.affiliates.new_conversion',
            'status' => 1,
            'slug' => 'new_conversion',
            'name' => 'New conversion',
        ],
		'approved_conversion' => [
            'subject' => 'Congrats! Your conversion has been approved',
            'content' => 'mails.affiliates.approved_conversion',
            'status' => 1,
            'slug' => 'approved_conversion',
            'name' => 'Approve conversion',
        ],
		'denied_conversion' => [
            'subject' => 'Your conversion has been rejected.',
            'content' => 'mails.affiliates.denied_conversion',
            'status' => 1,
            'slug' => 'denied_conversion',
            'name' => 'Denied conversion',
        ],
		'commission_payout' => [
            'subject' => 'Congrats! You’ve got new commission payout',
            'content' => 'mails.affiliates.commission_payout',
            'slug' => 'commission_payout',
            'status' => 1,
            'name' => 'Payment notification ',
        ],
        'invitation_affiliate' => [
            'subject' => 'Welcome to our Affiliate program',
            'content' => 'mails.affiliates.invitation_affiliate',
            'type' => 7,
            'status' => 1,
            'slug' => 'invitation_affiliate',
            'name' => 'Invitation Affiliate',
        ],
        'enter_payment_detail_alert' => [
            'subject' => 'Please fill in your payment details for our affiliate program',
            'content' => 'app.pages.email.template.notice_enter_payment_information',
            'type' => 8,
            'status' => 1,
            'slug' => 'enter_payment_detail_alert',
            'name' => 'Enter Payment Detail Alert',
        ],
        'verify_affiliate' => [
            'subject' => '[{brand_name}] Verify your email address',
            'content' => 'app.pages.email.template.verify_affiliate',
            'type' => 9,
            'status' => 1,
            'slug' => 'verify_affiliate',
            'name' => 'Verify affiliate',
        ],
    ];
