<?php
    return [
        "popupType" => "basic",
        "imgSrc" => "checkout/1632716394_bixgrow-default-popup-img.jpg",
        "onClickLink" => "",
        "titleText" => "Invite your friends and get a reward",
        "titleFontSize" => 18,
        "titleColor" => "#ff9900",
        "textContent3" => "Share your link with your friends and earn {commission_amount} commission whenever they make a purchase !",
        "textContent2" => "Share your link with your friends and earn 5% commission whenever they make a purchase !",
        "contentFontSize" => 13,
        "contentColor" => "#000",
        "btnText12" => "Get Started",
        "btnText3" => "Activate & Get my link",
        "imgHeight" => 200,
        "imgWidth" => 450,
        "btnColor" => "#fff",
        "btnBg" => "#ff9900",
        "btnConer" => 10,
        "newtab1" => 1,
        "newtab2" => 1,
        "closeOnBg" => 0,
        "embededInPage" =>0,
        "showOnce" => 0,
        "showArray" => ['Referral Link','Coupon Code'],
        "shareArray" => ['Facebook','Twitter','Pinterest', 'Linkedln'],
        "referralLinkLabel" => "Afiliate Link:",
        "referralLink" => "https://howardleo.myshopify.com/?bg_ref=refcode",
        "couponCode" => "DISCOUNTCODE",
        "couponCodeLabel" => "Coupon Code:",
        "CopyText" => "Copy",
        "ExtraCss" => "",
        "sharringMsg" => "Please click this",
        "showIfMoreThan" => 0,
        "program" => null,
        "pathCDN" => null
    ];
