<?php

return [
        "name" => "basicObj",
        "aside" => [
            "bgImg3" => "https://bixgrow.s3.us-west-2.amazonaws.com/asides/1629873728_login-visual-2.svg",
            "bgImg2" => "",
            "bgAside3" => "#b3e0f2",
            "bgAside2" => "#fafcfe",
            "textContent" => "<h1 style=\"text-align: center;\">&nbsp;</h1>\n<h1 style=\"text-align: center;\">&nbsp;</h1>\n<h1 style=\"text-align: center;\">&nbsp;</h1>\n<h1 style=\"text-align: center;\"><span style=\"font-size: 36pt; color: #000000;\"><strong>Welcome to {brand_name}!</strong></span></h1>\n<h2 style=\"text-align: center;\"><span style=\"color: #000000; font-size: 24pt;\">Join our affiliate program !</span></h2>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>",
            "overlay3" => 3,
            "overlay2" => 0,
        ],
        "logo" => [
            "isShow" => false,
            "width" => 10
        ],
        "bgAndBorder" => [
            "bg" => "#ffffff",
            "borderSize" => 0,
            "borderColor" => "#e8e9f2",
            "borderRadius" => 10,
        ],
        "titleAndDescription" => [
            "title" => [
                "text" => "Sign Up",
                "align" => "text-center",
                "color" => "#000000",
                "font_family" => "Poppins",
                "font_size" => 36,
                "font_weight" => "bold",
                "font_style" => "normal",
            ],
        ],
        "button" => [
            "submittext" => "Submit",
            "buttonAlign" => "fullW",
            "color" => "#fff",
            "backgroundColor" => "#000000",
            "borderColor" => "#000000",
            "borderRadius" => 10,
        ],
        "captcha" => [
            "isShow" => false,
            "theme" => "light",
        ],
        "bgHeaderTemplate1" =>"",
        "detailObj" => [
            "mainHeading" => "BENEFITS",
            "align" => "text-center",
            "background" => "#ebedf38c",
            "color" => "#000000",
            "fontfamily" => "Poppins",
            "isShow" => true,
            "checkmark" =>"#000000",
            "detailText" => [
                [
                    "label" => "Reward",
                    "content" => "{commission_type}",
                ],
                [
                    "label" => "Reward value",
                    "content" => "{commission_amount}",
                ],
                [
                    "label" => "Cookie days",
                    "content" => "{cookie_days}",
                ],
            ],
        ],
        "customInput" => [
            "labelFamily" => "Poppins",
            "labelColor" => "#3F4254",
            "fontWeight" => "normal",
            "fontSize" => 14,
            "fontStyle" => "normal",
            "inputColor" => "#f3f6f9",
            "borderColor" => "#f3f6f9",
        ],
        "customcss" => "",
        "model" => [
            "first_name" => "",
            "last_name" => "",
            "email" => "",
            "password" => "",
            "password_confirmation" => "",
            "company" => "",
            "address" => "",
            "city" => "",
            "zipcode" => "",
            "state" => "",
            "country" => "",
            "phone" => "",
            "facebook" => "",
            "youtube" => "",
            "instagram" => "",
            "twitter" => "",
            "website" => "",
            "personal_detail" => "",
        ],
        "tag" => "div",
        "schema" => [
            "fields" => [
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "First Name",
                    "model" => "first_name",
                    "placeholder" => "John",
                    "required" => true,
                    "visible" => true,
                    "disableEdit" => true,
                    "styleClasses" => ["apply-font-labelInput"],
                    "validator" => "required",
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Last Name",
                    "model" => "last_name",
                    "placeholder" => "Doe",
                    "required" => true,
                    "visible" => true,
                    "disableEdit" => true,
                    "styleClasses" => ["apply-font-labelInput"],
                    "validator" => "required",
                ],
                [
                    "type" => "input",
                    "inputType" => "email",
                    "label" => "Email Address",
                    "model" => "email",
                    "placeholder" => "Example@gmail.com...",
                    "required" => true,
                    "visible" => true,
                    "disableEdit" => true,
                    "styleClasses" => ["apply-font-labelInput"],
                    "validator" => "required",
                ],
                [
                    "type" => "input",
                    "inputType" => "password",
                    "label" => "Password",
                    "model" => "password",
                    "placeholder" => "",
                    "required" => true,
                    "visible" => true,
                    "disableEdit" => true,
                    "styleClasses" => ["apply-font-labelInput"],
                    "min" => 6,
                    "validator" => ["string"],
                ],
                [
                    "type" => "input",
                    "inputType" => "password",
                    "label" => "Password Confirmation",
                    "model" => "password_confirmation",
                    "placeholder" => "",
                    "required" => true,
                    "visible" => true,
                    "disableEdit" => true,
                    "styleClasses" => ["apply-font-labelInput"],
                    "min" => 6,
                    "validator" => ["string"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Company",
                    "model" => "company",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Address",
                    "model" => "address",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "City",
                    "model" => "city",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Zip Code",
                    "model" => "zipcode",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "State",
                    "model" => "state",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "select",
                    "inputType" => "text",
                    "label" => "Country",
                    "model" => "country",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "Number",
                    "label" => "Phone",
                    "model" => "phone",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Facebook",
                    "model" => "facebook",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Youtube",
                    "model" => "youtube",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Instagram",
                    "model" => "instagram",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Twitter",
                    "model" => "twitter",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Website",
                    "model" => "website",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
                [
                    "type" => "input",
                    "inputType" => "text",
                    "label" => "Personal detail",
                    "model" => "personal_detail",
                    "placeholder" => "",
                    "required" => false,
                    "visible" => false,
                    "disableEdit" => false,
                    "styleClasses" => ["apply-font-labelInput"],
                ],
            ],
        ],

];
