<?php
return[
    'terms' => '<p>Welcome to {brand_name}! Thank you for deciding to become a member of our affiliate program.&nbsp;</p>
    <p><br />The following terms and conditions apply to anyone accessing or using the Program, whether as a merchant (&ldquo;we&rdquo; or &ldquo;merchant&rdquo;) or as an affiliate (&ldquo;you&rdquo; or &ldquo;affiliate&rdquo;) who refers customers to use the merchant\'s product or service.&nbsp;</p>
    <p><br />By joining the program, affiliates accept to use the Program in the manner stated in these Terms and Conditions and are bound by them. You are not authorized to register as an affiliate or participate in the Program in any way if you do not agree to these Terms and Conditions in their entirety.</p>
    <p><br /><strong>1. Approve &amp; Deny the Registration</strong></p>
    <p><br />In our sole and absolute discretion, we reserve the right to approve or deny ANY Affiliate Program Registration. For the denial of your Affiliate Program Registration, you will have no legal recourse against us.</p>
    <p><br /><strong>2. Affiliate Links &amp; Coupon</strong></p>
    <p><br />Although an affiliate link is generated automatically, you can also create one for a single product or collection. If customers clicks on someone else\'s affiliate links and afterwards clicks on yours, it\'s yours that counts.&nbsp; <br />On the dashboard, affiliates may or may not be assigned to one discount code, with specifics and usage clarified. You will not receive a double commission if a customer clicks on the affiliate link and then uses the coupon code. If you have not been assigned a branded coupon, you aren\'t authorized to advertise it.&nbsp;<br />Affiliates may also promote the merchant\'s website on social media platforms such as Facebook and Instagram, as well as in print publications such as magazines and newspapers.</p>
    <p><br /><strong>3. Commission &amp; Payouts</strong></p>
    <p><br />If you refer a consumer to our website and they place an order, you will be paid a commission based on the Commission structure. The commission amount is determined by the order value and does not include any additional fees (tax, shipping cost, etc.).&nbsp;<br />You must set payment details in your affiliate account settings to get the commission.&nbsp;<br />Payments will be made only for transactions that have been completed successfully. The Affiliate Program is regulated by a fair usage policy, which allows the merchant to examine each and every conversion. Status of the commission is displayed in the Conversions tab and any paid commission will be listed on the Payouts tab. Transactions that result in chargebacks or refunds are not eligible for payment.</p>
    <p><br /><strong>4. Marketing Resources</strong></p>
    <p><br />Through the Marketing Resources tab, we may share promotional media with you, such as a banner, logo, or a specific collection promotion. To distribute on affiliate channels, you may either download the media or acquire the HTML embed code.</p>
    <p><br /><strong>5. Network</strong></p>
    <p><br />If the Network tab is enabled, affiliates can ask others to become their downline affiliates. If a downline affiliate successfully refers an order for the merchant store, the upline affiliate will receive a network commission based on the merchant\'s settings.&nbsp; <br />Share the network link with other affiliates to invite them to join the network, and each affiliate who clicks on the link and registers will become a downline affiliate.</p>
    <p><br /><strong>6. Cookie</strong></p>
    <p><br />We track customers who click on your link using cookies, thus, they must be using cookies so we can track them.&nbsp; <br />We cannot track an user who does not allow cookies or clears their cookies, so we cannot pay rewards on that person\'s activity.&nbsp; <br />Cookie duration is specified in the affiliate signup form. When a customer clicks on the affiliate\'s link or apply the coupon, the tracking day begins. During the cookie period, every purchase made by this client on the merchant\'s website will result in commissions to the affiliate (the customer will not be required to click on the affiliate link).</p>
    <p><br /><strong>7. Exclusion from Affiliate Program</strong></p>
    <p><br />If an affiliate wants to be dismissed from the affiliate program, they can send an email to: {contact_email}.</p>
    <p><br /><strong>Go ahead and refer!</strong></p>
    <p><br />We\'re delighted you\'ve made it this far through this important information.&nbsp; <br />We wish you the best of luck. You can come back to these Affiliate Program terms and conditions at any time, and if you have any questions, send an email to {contact_email} for assistance.</p>
    ',
    'policy' => '<p><strong>This Privacy Policy of BixGrow: Affiliate Marketing explains how we gather and utilize personal data, as well as the rights that merchants, affiliates, and customers have over their data.</strong></p>
    <p><br />By participating in the Affiliate program, you agree to the rules outlined in this Privacy Policy, as well as all other terms and conditions. You must not access the affiliate marketing system if you do not agree to this Privacy Policy.&nbsp;<br />This Privacy Policy may be updated from time to time to reflect changes in our privacy practices or for other functional, legal, or regulatory reasons. You agree to the amended rules if you continue to use our affiliate program after these changes are made.</p>
    <p><br /><strong>Data gathered from Merchants</strong></p>
    <p><br />When a merchant uses the app, we are able to immediately access various sorts of information from their Shopify account, including email, first &amp; last names and shop information (shop domain, shop currency, shop location, etc.). We collect this information in order to offer you our Services, such as to verify your identity, contact you, provide customer assistance when you contact us, and send you advertising and marketing materials.</p>
    <p><br /><strong>Data gathered from Affiliates</strong></p>
    <p><br />We collect some information from affiliates when they registers for a program such as email, personal information, payment details and social network information, so as to inform merchants. The data would allow the merchant to assess the affiliate\'s background and potential, as well as examine specific app activity and contact the affiliate if necessary.</p>
    <p><br /><strong>Data gathered from Customers when visiting merchant website</strong></p>
    <p><br />When customers visit a merchant\'s website and place an order, the BixGrow system collects information about the sale, such as the order amount, order items, order ID, etc. to track conversions.</p>
    <p><br /><strong>Cookie</strong></p>
    <p><br />"Cookies" and other tracking technologies are used on some of our site pages. Cookies are little files that are placed on your hard disk to assist us in analyzing the movement of our web pages and customizing our services. These cookies are used to save information such as visitor preferences and the pages of the website they browsed or visited.<br />We recommend that you leave cookies turned on because they allow you to use some of the affiliate marketing system\'s most important features.</p>
    <p><br /><strong>Data Sharing</strong></p>
    <p><br />We value your privacy and take precautions to protect it. Except as specified in this privacy policy, we do not disclose your personal information with other parties. We may share your personal information with third-party service providers that we hire to do certain tasks for us, such as email marketing, data analysis and other marketing support. Third-party service providers have access to personal information only as long as it is necessary for them to perform their functions, and they must process it in line with this Privacy Policy.</p>
    <p><br /><strong>Online Privacy Protection for Children</strong></p>
    <p><br />Children under the age of 13 are not permitted to use or access the Services. Children under the age of 13 are not deliberately collected personal information by BixGrow. By sending information to BixGrow, you represent that you are at least 13 years old . If you are under 13, you may only use the Site and Services with your parent or guardian\'s permission.</p>
    <p><br /><strong>Contact Information</strong></p>
    <p><br />Please contact us at support@bixgrow.com if you have any queries about our privacy policy or would like to file a complaint about how we handle your personal information.</p>
    '
];